<?php

/**
 * @file
 * Allows users to manage grades.
 */

use Drupal\Core\Cache\Cache;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;
use Drupal\Core\Form\FormStateInterface;

const GRADE_ITEM_VALUATION_NUMERIC = 'numeric';
const GRADE_ITEM_VALUATION_STRING = 'string';

/**
 * Implements hook_help().
 */
function gradebook_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.gradebook':
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The Gradebook suite of modules allows users to manage <em>grade books</em> ...') . '</p>';
      return $output;

    case 'entity.grade_item.collection':
      return '<p>' . t('Grade items provide grades for activities both online and offline.') . '</p>';

    case 'entity.grade_item_data.collection':
      return '<p>' . t('Grade item data provide additional information which may be shared between grade items and categories.') . '</p>';

    case 'entity.grade_category.collection':
      return '<p>' . t('Grade categories allows for the classification of grades.') . '</p>';

    case 'entity.grade_letter_set.collection':
      return '<p>' . t('List of all grade letter sets.') . '</p>';

    case 'entity.grade_letter_set.list_form':
      return '<p>' . t('List of grade letters in set.') . '</p>';
  }
}

/**
 * Implements hook_grade_valuation_info().
 */
function gradebook_grade_valuation_info() {
  return [
    GRADE_ITEM_VALUATION_NUMERIC => [
      'label' => 'Numeric',
      'description' => t('The grade is represented by a number.'),
      'widget_callback' => '',
    ],
    GRADE_ITEM_VALUATION_STRING => [
      'label' => 'String',
      'description' => t('The grade is a textual feedback only.'),
      'widget_callback' => '',
    ],
  ];
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Adds group options to the node type form.
 *
 * @see NodeTypeForm::form().
 * @see gradebook_form_node_type_form_submit().
 */
function gradebook_form_node_type_form_alter(&$form, FormStateInterface $form_state) {
  // @todo: attach behaviour
  $form['gradebook'] = array(
    '#type' => 'details',
    '#title' => t('Gradebook'),
    '#group' => 'additional_settings',
  );

  $form['gradebook']['gradebook_node_type'] = array(
    '#type' => 'checkbox',
    '#title' => t('Enable grading.'),
    '#default_value' => \Drupal::service('gradebook.manager')->isGradebookEnabled($form_state->getFormObject()->getEntity()->id()),
    '#description' => t('Content will be included in relevant Gradebook actions.'),
  );

  $form['actions']['submit']['#submit'][] = 'gradebook_form_node_type_form_submit';
}

/**
 * Submit callback for the node type form to save the gradebook settings.
 */
function gradebook_form_node_type_form_submit($form, FormStateInterface $form_state) {
  \Drupal::configFactory()->getEditable('gradebook.settings')->set(
    'gradebook_entity.' . $form_state->getFormObject()->getEntity()->id(),
    $form_state->getValue('gradebook_node_type'))->save();
}

