<?php

/**
 * @file
 * Allows users to manage grade scales.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function grade_scale_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.grade_scale':
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The Grade Scale module allows users to create ...') . '</p>';
     return $output;

    case 'entity.grade_scale.collection':
    case 'grade_scale.add':
    case 'entity.grade_scale.edit_form':
      return '<p>' . t('TODO: grade_scale_help() ...') . '</p>';
  }
}

